name: Build & Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:   # cho phép bấm nút "Run workflow" thủ công

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}:latest
          echo "Building and pushing $IMAGE_ID"
          docker build -t $IMAGE_ID .
          docker push $IMAGE_ID
